### ISSUE TITLE
Russian translation of community video

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/transcriptions#14]

**Comment by AlonaBludova** [comment]
**0:00:00.269,0:00:02.060**
Привет, я Эдди!

**0:00:02.060,0:00:04.189**
Наше сообщество называется EddieHub

**0:00:04.189,0:00:09.299**
Мы верим в то, что сотрудничество должно быть на первом месте,
а код - на втором

**0:00:09.299,0:00:13.570**
Мы - инклюзивное сообщество с открытым исходным кодом,
и сосредоточены на поддержке друг друга

**0:00:13.570,0:00:15.830**
Независимо от того, на каком этапе развития вы находитесь

**0:00:15.830,0:00:19.290**
Помните: даже если у вас есть всего 1 месяц опыта,

**0:00:19.290,0:00:22.370**
существует человек, который чувствует себя так, как вы месяц назад

**0:00:22.370,0:00:26.360**
Помощь другим - это отличный способ учиться
и развивать свою сеть

**0:00:26.360,0:00:30.220**
На моем YouTube канале вы найдете множество
видео-руководств по открытому исходному коду и GitHub

**0:00:30.220,0:00:35.820**
Также я веду прямые трансляции, вовлекаю вас в работу
с открытым исходным кодом и помогаю получить зеленые квадраты

**0:00:35.820,0:00:39.070**
Кроме того, я приглашаю замечательных гостей,
чтобы они могли пообщаться с нами

**0:00:39.070,0:00:42.480**
У нас также есть организация GitHub,
к которой вы можете присоединиться

**0:00:42.480,0:00:46.510**
Просто сделайте запрос в поддержку
с пометкой “пригласить меня в организацию”

**0:00:46.510,0:00:51.630**
И GitHub Action сделает всю магию
и отправит вам приглашение

**0:00:51.630,0:00:54.510**
Помните, если вы хотите видеть других людей -
вы являетесь частью нашей организации

**0:00:54.510,0:00:57.800**
Вы должны сделать это общедоступным в своем профиле,
только вы можете это сделать

**0:00:57.800,0:01:03.030**
В нашей организации GitHub есть много
TypeScript проектов от ботов Discord,

**0:01:03.030,0:01:04.579**
которые готовы к вашему реагированию

**0:01:04.579,0:01:06.189**
И множество другого

**0:01:06.189,0:01:09.299**
Если вы хотите участвовать, наше сообщество
поможет вам

**0:01:09.299,0:01:13.429**
Вы также можете предоставить для обзора ваш проект с открытым исходным кодом.
Это могу сделать я или сообщество

**0:01:13.429,0:01:18.899**
Сделайте это, подняв запрос в 
в нашей службе поддержки с пометкой "посмотрите

**0:01:18.899,0:01:22.409**
мой проект с открытым исходным кодом”
Если вы хотите общаться между выходом видео на YouTube,

**0:01:22.409,0:01:25.329**
прямыми трансляциями, и вашими зелеными
квадратами с открытым исходным кодом,

**0:01:25.329,0:01:28.779**
У нас также есть Discord, куда вы можете перейти
и присоединиться к беседе

**0:01:28.779,0:01:32.060**
Будет много интересных событий
и тем в будущем

**0:01:32.060,0:01:36.119**
Если вы хотите узнать больше об открытом исходном коде,
сотрудничайте и улучшайте свои технические и

**0:01:36.119,0:01:37.399**
коммуникативные навыки

**0:01:37.399,0:01:39.270**
Присоединяйтесь к нашему сообществу, чтобы ускорить развитие своей карьеры

**0:01:39.270,0:01:40.749**
С нетерпением жду встречи с вами!

**Comment by AlonaBludova** [comment]
![screen](https://user-images.githubusercontent.com/70797447/107017125-cf500e00-67af-11eb-9039-e534a27e0a52.jpg)
btw, this link doesn't work

**Comment by eddiejaoude** [comment]
oh no, we forgot to update it 😱 - thank you 👍

**Comment by AlonaBludova** [comment]
_rephrase some for easier understanding_ 

**0:00:51.630,0:00:54.510**
Помните, если вы хотите видеть других людей,
являющихся частью нашего сообщества

**0:00:54.510,0:00:57.800**
вы должны сделать это общедоступным в своем профиле.
Только вы можете это сделать


**0:01:09.299,0:01:13.429**
Вы также можете предоставить ваш open source проект
для обзора мне или сообществу


**0:01:32.060,0:01:36.119**
Если вы хотите узнать больше об открытом исходном коде,
сотрудничестве и улучшить свои технические и

**Comment by eddiejaoude** [comment]
Thanks @AlonaBludova . Could you paste the whole thing in again with your changes, to avoid me making a mistake when combining it together

**Comment by AlonaBludova** [comment]
0:00:00.269,0:00:02.060
Привет, я Эдди!

0:00:02.060,0:00:04.189
Наше сообщество называется EddieHub

0:00:04.189,0:00:09.299
Мы верим в то, что сотрудничество должно быть на первом месте,
а код - на втором

0:00:09.299,0:00:13.570
Мы - инклюзивное сообщество с открытым исходным кодом,
и сосредоточены на поддержке друг друга

0:00:13.570,0:00:15.830
Независимо от того, на каком этапе развития вы находитесь

0:00:15.830,0:00:19.290
Помните: даже если у вас есть всего 1 месяц опыта,

0:00:19.290,0:00:22.370
существует человек, который чувствует себя так, как вы месяц назад

0:00:22.370,0:00:26.360
Помощь другим - это отличный способ учиться
и развивать свою сеть

0:00:26.360,0:00:30.220
На моем YouTube канале вы найдете множество
видео-руководств по открытому исходному коду и GitHub

0:00:30.220,0:00:35.820
Также я веду прямые трансляции, вовлекаю вас в работу
с открытым исходным кодом и помогаю получить зеленые квадраты

0:00:35.820,0:00:39.070
Кроме того, я приглашаю замечательных гостей,
чтобы они могли пообщаться с нами

0:00:39.070,0:00:42.480
У нас также есть организация GitHub,
к которой вы можете присоединиться

0:00:42.480,0:00:46.510
Просто сделайте запрос в поддержку
с пометкой “пригласить меня в организацию”

0:00:46.510,0:00:51.630
И GitHub Action сделает всю магию
и отправит вам приглашение

0:00:51.630,0:00:54.510
Помните, если вы хотите видеть других людей,
являющихся частью нашего сообщества,

0:00:54.510,0:00:57.800
вы должны сделать это общедоступным в своем профиле.
Только вы можете это сделать

0:00:57.800,0:01:03.030
В нашей организации GitHub есть много
TypeScript проектов от ботов Discord,

0:01:03.030,0:01:04.579
которые готовы к вашему реагированию

0:01:04.579,0:01:06.189
И множество другого

0:01:06.189,0:01:09.299
Если вы хотите участвовать, наше сообщество
поможет вам

0:01:09.299,0:01:13.429
Вы также можете предоставить ваш open source проект
для обзора мне или сообществу

0:01:13.429,0:01:18.899
Сделайте это, подняв запрос в
в нашей службе поддержки с пометкой "посмотрите

0:01:18.899,0:01:22.409
мой проект с открытым исходным кодом”
Если вы хотите общаться между выходом видео на YouTube,

0:01:22.409,0:01:25.329
прямыми трансляциями, и вашими зелеными
квадратами с открытым исходным кодом,

0:01:25.329,0:01:28.779
У нас также есть Discord, куда вы можете перейти
и присоединиться к беседе

0:01:28.779,0:01:32.060
Будет много интересных событий
и тем в будущем

0:01:32.060,0:01:36.119
Если вы хотите узнать больше об открытом исходном коде,
сотрудничестве и улучшить свои технические и

0:01:36.119,0:01:37.399
коммуникативные навыки

0:01:37.399,0:01:39.270
Присоединяйтесь к нашему сообществу, чтобы ускорить развитие своей карьеры

0:01:39.270,0:01:40.749
С нетерпением жду встречи с вами!

**Comment by AlonaBludova** [comment]
@eddiejaoude sure, sorry for this confuse! please, look at above

**Comment by eddiejaoude** [comment]
Thank you @AlonaBludova 🤓
