### ISSUE TITLE
github organization link broken

### ISSUE THREAD

**Issue by rish-singhal** [EddieHubCommunity/transcriptions#15]
The link for GitHub organization is broken in the welcoming message "It's great having you contribute to this project"

So, it needs some updates in GitHub actions file

**Comment by eddiejaoude** [comment]
This is still an error, I will reopen 

See here too https://github.com/EddieHubCommunity/transcriptions/issues/14#issuecomment-773920172

**Comment by eddiejaoude** [comment]
This is now fixed. Thank you for raising
